### ISSUE TITLE
Reduced dataset for deployment

### ISSUE THREAD

**Issue by Zethson** [Zethson/dark-proteome-visualization#19]
The dark proteins dataset is far too big for a 1GB Ram VPS. 
I should reduce it using a random sample of 25k or something.

**Comment by Zethson** [comment]
We need reduced datasets anyways for our D3 visualizations. More than 25k datapoints will crash the client browser.
But if you have any suggestions - always welcome!

**Comment by brettvanderwerff** [comment]
I don't know the details of what you guys are doing too much, so ignore if this is not helpful. The memory thing just stuck out to me and I see you are using a for loop to read a csv from disk. If you can selectively query the db switching to SQL based on what the pages want that is usually a much better speed wise and does not exhaust memory as fast as reading a whole csv in at once. Reading data from a straight csv is not done too often with web stuff, but maybe there is not a better way here.

**Comment by Zethson** [comment]
I'm afraid that this is not an option here. But we'll keep it in mind.

**Comment by Zethson** [comment]
https://github.com/Zethson/dark-proteome-visualization/commit/769c4ca927c479d8eb35e3581f088b6b6a99c5db
